services:
  selenium:
    image: seleniarm/standalone-chromium
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: 3gb
    volumes:
      - ./shared_downloads:/home/seluser/Downloads

  python:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      # - type: bind
      #   source: ./analizeCode
      #   target: /home/jovyan/work
      - .:/home/jovyan/work
      - ./shared_downloads:/home/jovyan/work/shared_downloads  # ← 追加  
    stdin_open: true    
    tty: true
    ports:
      - 8888:8888    
    depends_on:
      - selenium
    environment:
      - SELENIUM_HOST=selenium          
    command:  # 以下を指定することでトークンなしでアクセスできるようになる
      - "start-notebook.py"
      - "--IdentityProvider.token=''"

        
